// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Dropdown: typeof import('./src/components/virtual/dropdown.vue')['default']
    DropdownItem: typeof import('./src/components/virtual/dropdownItem.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon: typeof import('./src/components/icon/index.vue')['default']
    More: typeof import('./src/components/virtual/more.vue')['default']
    Tooltip: typeof import('./src/components/virtual/tooltip.vue')['default']
    Virtual: typeof import('./src/components/virtual/index.ts')['default']
    'VirtualDropdown.stories': typeof import('./src/components/virtual/VirtualDropdown.stories.ts')['default']
    'VirtualTooltip.stories': typeof import('./src/components/virtual/VirtualTooltip.stories.ts')['default']
  }
}
